name: üêã Auth Service | Docker

env:
  workdir: services/auth

on:
  push:
    paths: [ "services/auth/**", ".github/workflows/auth-service-docker-image.yml" ]
    branches: main

jobs:
  build:
    name: Build and Push Image
    runs-on: self-hosted
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t alpacron/auth:latest $workdir
    - name: Push the Docker image
      run: docker push alpacron/auth

  deploy:
    name: Deploy
    needs: build
    runs-on: self-hosted
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions-hub/kubectl@master
      env:
        KUBE_HOST: ${{ secrets.KUBE_HOST }}
        KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
        KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      with:
        args: rollout restart deployment -n rml auth-deployment
    - name: deploy
      run: echo "deploying started"
