name: ðŸ‹ Auth Service | Docker Build and Deploy Test => Production

env:
  workdir: services/auth

on:
  push:
    paths: [ "services/auth/**", ".github/workflows/auth-service-test-prod-deploy.yml", "tests/auth-test.jmx" ]
    branches: main

jobs:
  buildtest:
    name: Build and Push Test Image
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t alpacron/auth:test $workdir
    - name: Push the Docker image
      run: docker push alpacron/auth:test

  deploytest:
    name: Deploy Test
    needs: buildtest
    runs-on: self-hosted
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions-hub/kubectl@master
      env:
        KUBE_HOST: ${{ secrets.KUBE_HOST_TESTENV }}
        KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE_TESTENV }}
        KUBE_TOKEN: ${{ secrets.KUBE_TOKEN_TESTENV }}
      with:
        args: rollout restart deployment -n rml auth-deployment
    - name: deploy
      run: echo "deploying started"
    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash

  runtest:
    name: Run Tests
    needs: deploytest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Run JMeter Tests
      uses: rbhadti94/apache-jmeter-action@v0.5.0
      with:
        testFilePath: './tests/auth-test.jmx'
        outputReportsFolder: reports/
    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: reports/

  build:
    name: Build and Push Prod Image
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t alpacron/auth:latest $workdir
    - name: Push the Docker image
      run: docker push alpacron/auth

  deploy:
    name: Deploy Prod
    needs: build
    runs-on: self-hosted
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions-hub/kubectl@master
      env:
        KUBE_HOST: ${{ secrets.KUBE_HOST }}
        KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
        KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      with:
        args: rollout restart deployment -n rml auth-deployment
    - name: deploy
      run: echo "deploying started"
